font_family     Jetbrains Mono

font_size 16
modify_font cell_height 130%

hide_window_decorations titlebar-only
draw_minimal_borders yes
inactive_text_alpha 0.75

cursor_shape block
cursor_blink_interval -1
cursor_shape_unfocused hollow

# Set to a non 0 integer to activate cursor trails
cursor_trail 0
cursor_trail_decay 0.05 0.2
cursor_trail_start_threshold 0

# shell
shell fish
shell_integration no-cursor
allow_remote_control yes

# This will actually disable the tab bar
tab_bar_edge bottom
tab_bar_align center
tab_bar_style fade
tab_bar_min_tabs 1

repaint_delay 10
input_delay 3

map cmd+o launch --type overlay --allow-remote-control --copy-env=yes  sh -c "~/.config/kitty/scripts/session-picker.sh windows"

enabled_layouts splits,stack

map cmd+enter next_layout
map cmd+x next_layout
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

map cmd+t new_tab_with_cwd

map cmd+p previous_tab
map cmd+n next_tab

map cmd+d launch --cwd=current --location=vsplit
map cmd+shift+d launch --cwd=current --location=hsplit

map cmd+w close_window
map cmd+shift+n new_os_window_with_cwd
map cmd+r set_tab_title
map cmd+shift+comma load_config_file

map cmd+left neighboring_window left
map cmd+down neighboring_window down
map cmd+up neighboring_window up
map cmd+right neighboring_window right

# Theme
include themes/tokyo_night_night.conf
