general.import = [ "~/.config/themes/current/alacritty.toml" ]

general.live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
normal = { family = "TX-02" }
bold   = { family = "TX-02" }
italic = { family = "TX-02" }
size   = 12

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.90

[keyboard]
bindings = [
	{ key = "F11", action = "ToggleFullscreen" }
]
