# import = [ "~/.config/alacritty/themes/gruvbox.toml" ]
import = [ "~/.config/alacritty/themes/tokyonight.toml" ]

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
    { key = "F11", action = "ToggleFullscreen" }
]

[font]
normal = { family = 'Cascadia Code NF' }

