import = [ "~/.config/alacritty/tokyonight.toml" ]

[env]
TERM = "xterm-256color"

[keyboard]

[font]
normal = { family = 'Fira Code Retina' }
offset = { y = 10 }
size = 15

[window]
# opacity = 0.93
option_as_alt="Both"

