import = [ 
    # "~/.config/alacritty/themes/simple.toml" ,
    # "~/.config/alacritty/themes/nightfly.toml" ,
    # "~/.config/alacritty/themes/coolnight.toml" ,
    # "~/.config/alacritty/themes/gruvbox.toml" ,
    "~/.config/alacritty/themes/tokyonight.toml" ,
    # "~/.config/alacritty/themes/catppuccin.toml",
    # "~/.config/alacritty/themes/rosepine.toml" 
]

[env]
TERM = "xterm-256color"

[keyboard]

[font]
normal = { family = 'MesloLGL Nerd Font Mono'}
size = 15

[window]
# opacity = 0.93
option_as_alt="Both"
