[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
    { key = "F11", action = "ToggleFullscreen" }
]

[font]
normal = { family = 'JetBrainsMonoNerdFontMono' }

[colors]
[colors.primary]
background = '#000000'
foreground = '#e0e0e0'
