general.import = [ "~/.config/themes/current/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Maple Mono" }
bold =   { family = "Maple Mono" }
italic = { family = "Maple Mono" }
size = 9

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.90

[keyboard]
bindings = [
	{ key = "F11", action = "ToggleFullscreen" }
]
