#!/usr/bin/env bash

get_project_name() {
    local dir=$(pwd)
    while [ "$dir" != "/" ]; do
        if [ -d "$dir/.git" ]; then
            basename "$dir"
            return
        fi
        dir=$(dirname "$dir")
    done
}

project_name=$(get_project_name)

if [ -n "$TMUX" ]; then
    if [ -n "$project_name" ]; then
        tmux rename-session -t "$(tmux display-message -p '#S')" "$project_name"
    fi
else
    tmux attach 2>/dev/null && exit 0
    if [ -n "$project_name" ]; then
        tmux new-session -ds "$project_name" -n Code
    else
        tmux new-session -ds "temp" -n Code
    fi
    tmux send-keys -t "${project_name:-temp}:Code" "nvim" Enter

    tmux new-window -t "${project_name:-temp}" -n Shell
    tmux new-window -t "${project_name:-temp}" -n Agent
    tmux send-keys -t "${project_name:-temp}:Agent" "opencode" Enter
    tmux select-window -t "${project_name:-temp}:1"
    tmux attach -t "${project_name:-temp}"
fi
