# Ensure homebrew binaries are in PATH
set-environment -g PATH "/opt/homebrew/bin:$PATH"

unbind C-b
set -g prefix C-a
set -g prefix2 C-\;
bind C-a send-prefix
bind C-\; send-prefix

set -g status-style 'bg=#333333 fg=#5eacd3' 
set -g status-left-length 50

set -g base-index 1
set -g mouse on
set -g escape-time 0
set -g renumber-windows on

# Enable extended keys
set -s extended-keys on
set -g extended-keys always
set -as terminal-features 'xterm*:extkeys'

# Copy stuff
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

set -g default-terminal "tmux-256color"

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Reload configuration
bind r source ~/.config/tmux/tmux.conf

bind x kill-pane

# Most important part of the tmux THE "session-picker".
bind C-o display-popup -E -w 80% -h 60% "~/.config/tmux/session-picker.sh"
bind o display-popup -E -w 80% -h 60% "~/.config/tmux/session-picker.sh"
# bind C-o neww "~/.config/tmux/session-picker.sh"
# bind o neww "~/.config/tmux/session-picker.sh"

bind C-p previous-window
bind C-n next-window

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

