# Ensure homebrew binaries are in PATH
set-environment -g PATH "/opt/homebrew/bin:$PATH"

unbind C-b
set -g prefix C-a
set -g prefix2 C-\;
bind C-a send-prefix
bind C-\; send-prefix

# set -g status-style 'bg=#333333 fg=#5eacd3' 
# set -g status-left-length 50

set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=black bg=white  "
set -g window-status-current-style "fg=colour255,bg=default,bold"
set -g window-status-separator ""
set -g window-status-format "#[fg=colour240]#[default] #I:#W#{?window_flags,#{window_flags},} #[fg=colour240]#[default]"
set -g window-status-current-format "#[fg=colour252]#[default] #I:#W#{?window_flags,#{window_flags},} #[fg=colour252]#[default]"
set -g status-interval 5
set -g status-left "#S"
set -g status-right ""

set -g base-index 1
set -g mouse on
set -g escape-time 0
set -g renumber-windows on

# Enable extended keys
set -s extended-keys on
set -g extended-keys always
set -as terminal-features 'xterm*:extkeys'

# Copy stuff
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

set -g default-terminal "tmux-256color"

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Reload configuration
bind r source ~/.config/tmux/tmux.conf

bind x kill-pane
bind z resize-pane -Z
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind H resize-pane -L 20
bind J resize-pane -D 20
bind K resize-pane -U 20
bind L resize-pane -R 20

# Most important part of the tmux THE "session-picker".
# bind C-o display-popup -E -w 80% -h 60% "~/.config/tmux/session-picker.sh"
# bind o display-popup -E -w 80% -h 60% "~/.config/tmux/session-picker.sh"
bind C-o neww "~/.config/tmux/session-picker.sh"
bind o neww "~/.config/tmux/session-picker.sh"

bind C-p previous-window
bind C-n next-window
bind C-c new-window
bind C-x kill-pane
