# I Control tmux using CMD key in macos.
# Checkout terminal configs.
# Comment

# Ensure homebrew binaries are in PATH
set-environment -g PATH "/opt/homebrew/bin:$PATH"

unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g status-style 'bg=default fg=color10'
set -g status-left-length 50

set -g base-index 1
set -g mouse on
set -g escape-time 0
set -g renumber-windows on

# Enable extended keys
set -s extended-keys on
set -g extended-keys always
set -as terminal-features 'xterm*:extkeys'

# Copy stuff
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

set -g default-terminal "tmux-256color"

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Reload configuration
bind r source ~/.config/tmux/tmux.conf

bind x kill-pane

# Most important part of the tmux.
bind C-p display-popup -E -w 80% -h 60% "~/.config/tmux/session-picker.sh"
# bind C-p neww "~/.config/tmux/session-picker.sh"
# bind C-p split-window -h -l 35 -b "zsh ~/.config/tmux/session-picker.sh"

