#!/usr/bin/env bash

alias gs='git status'
alias gst='git status'
alias gdd='git diff HEAD'
alias gg='git push origin $(git_current_branch)'
export GOPRIVATE=gitlab.snappcloud.io
export PATH="/opt/homebrew/opt/mysql-client/bin:$PATH"

if command -v brew &>/dev/null
then
    eval $(brew shellenv)
fi

export NEOVIDE_FORK=1
export NEOVIDE_TABS=0
export PATH="/usr/local/go/bin:$PATH"
export PATH="$HOME/go/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$PATH:$HOME/prg/bin"
export DOTFILES="$HOME/w/dotfiles"
export PATH="$PATH:$DOTFILES/bin"
export PATH="$PATH:$HOME/.zig"

alias svpn='sudo openfortivpn  --otp $(totpgen ADS)'

[ -f "$HOME/cargo/env" ] && . "$HOME/.cargo/env"
export color_prompt='yes'

if [ -n "$BASH" ]; then
    export PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u:\[\033[01;34m\]\w\[\033[00m\]\$ '
fi

ascii_art=$(cat << 'EOF'
    ___              _                            ___         __  
   /   |  ____ ___  (_)____________  ____  ____ _/   |  _____/ /__
  / /| | / __ `__ \/ / ___/ ___/ _ \/_  / / __ `/ /| | / ___/ //_/
 / ___ |/ / / / / / / /  / /  /  __/ / /_/ /_/ / ___ |(__  ) ,<   
/_/  |_/_/ /_/ /_/_/_/  /_/   \___/ /___/\__,_/_/  |_/____/_/|_|  
                                                                  
EOF
)

# echo "$ascii_art"

