[env]
TERM = "xterm-256color"

[keyboard]

[font]
normal = { family = 'MesloLGL Nerd Font Mono'}
size = 15

[window]
# opacity = 0.93
option_as_alt="Both"

# Catppuccin
# [colors.primary]
# background = "#1e1e2e"
# foreground = "#cdd6f4"
# dim_foreground = "#7f849c"
# bright_foreground = "#cdd6f4"
#
# [colors.cursor]
# text = "#1e1e2e"
# cursor = "#f5e0dc"
#
# [colors.vi_mode_cursor]
# text = "#1e1e2e"
# cursor = "#b4befe"
#
# [colors.search.matches]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.search.focused_match]
# foreground = "#1e1e2e"
# background = "#a6e3a1"
#
# [colors.footer_bar]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.hints.start]
# foreground = "#1e1e2e"
# background = "#f9e2af"
#
# [colors.hints.end]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.selection]
# text = "#1e1e2e"
# background = "#f5e0dc"
#
# [colors.normal]
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#bac2de"
#
# [colors.bright]
# black = "#585b70"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#a6adc8"
#
# [colors.dim]
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#bac2de"
#
# [[colors.indexed_colors]]
# index = 16
# color = "#fab387"
#
# [[colors.indexed_colors]]
# index = 17
# color = "#f5e0dc"

[colors.primary]
background = '#011423'
foreground = '#CBE0F0'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = "#011423"
cursor = "#47FF9C"

[colors.normal]
black = "#214969"
red = "#E52E2E"
green = "#44FFB1"
yellow = "#FFE073"
blue = "#0FC5ED"
magenta = "#a277ff"
cyan = "#24EAF7"
white = "#24EAF7"

[colors.bright]
black = "#214969"
red = "#E52E2E"
green = "#44FFB1"
yellow = "#FFE073"
blue = "#A277FF"
magenta = "#a277ff"
cyan = "#24EAF7"
white = "#24EAF7"
