[general]
live_config_reload = true

[env]
TERM = "screen-256color"

[font]
size = 14

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window]
opacity = 0.93
decorations = "None"
dynamic_padding = true

[window.padding]
x = 3
y = 3

