[general]
live_config_reload = true

[env]
TERM = "screen-256color"

[font]
normal = { family = "FiraCode Nerd Font Mono" }
size = 14

[window]
opacity = 0.85
blur = true
decorations = "None"
dynamic_padding = true
startup_mode = "Maximized"
option_as_alt = "Both"
padding = { x = 3, y = 3 }

[colors.primary]
foreground = "#e1e1e1"
background = "#000000"
