[general]
live_config_reload = true

[env]
TERM = "screen-256color"

[font]
normal = { family = "TX-02", style = "Regular" }
bold = { family = "TX-02", style = "Bold" }
italic = { family = "TX-02", style = "Italic" }
bold_italic = { family = "TX-02", style = "Bold Italic" }
size = 14

[window]
opacity = 0.50
blur = true
decorations = "None"
dynamic_padding = true
startup_mode = "Maximized"
option_as_alt = "Both"

[window.padding]
x = 3
y = 3

[colors.primary]
foreground = "#e1e1e1"
background = "#000000"

