#!/usr/bin/env bash

set -e

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
XDG_CONFIG="$HOME/.config"

mkdir -p "$XDG_CONFIG"

rm -rf "$XDG_CONFIG/fish" \
        "$XDG_CONFIG/ghostty" \
        "$XDG_CONFIG/alacritty" \
        "$XDG_CONFIG/starship.toml" \
        "$XDG_CONFIG/nvim" \
        "$XDG_CONFIG/wezterm" \
        "$HOME/.zshrc" \
        "$HOME/.gitconfig"

mkdir -p "$XDG_CONFIG/ghostty"
ln -s "$DOTFILES_DIR/ghostty.config" "$XDG_CONFIG/ghostty/config"

mkdir -p "$XDG_CONFIG/alacritty"
ln -s "$DOTFILES_DIR/alacritty.toml" "$XDG_CONFIG/alacritty/alacritty.toml"

ln -s "$DOTFILES_DIR/starship.toml" "$XDG_CONFIG/"

ln -s "$DOTFILES_DIR/zshrc" "$HOME/.zshrc"

ln -s "$DOTFILES_DIR/.gitconfig" "$HOME/.gitconfig"

mkdir -p "$XDG_CONFIG/nvim"
ln -s "$DOTFILES_DIR/init.lua" "$XDG_CONFIG/nvim/init.lua"

mkdir -p "$XDG_CONFIG/wezterm"
ln -s "$DOTFILES_DIR/wezterm.lua" "$XDG_CONFIG/wezterm/"

mkdir -p "$XDG_CONFIG/fish"
ln -s "$DOTFILES_DIR/config.fish" "$XDG_CONFIG/fish/config.fish"


rm -rf $HOME/.tmux.conf
ln -s "$DOTFILES_DIR/tmux.conf" "$HOME/.tmux.conf"
rm -rf $HOME/.tmux-sessionizer
ln -s "$DOTFILES_DIR/tmux-sessionizer" "$HOME/.tmux-sessionizer"

rm -rf $HOME/.config/alacritty
mkdir -p $HOME/.config/alacritty
ln -s "$DOTFILES_DIR/alacritty.toml" "$HOME/.config/alacritty/alacritty.toml"

# VSCode (or Cursor) configs
if [ -d "$HOME/Library/Application Support/Cursor" ]; then
  rm -rf "$HOME/Library/Application Support/Cursor/User/keybindings.json"
  rm -rf "$HOME/Library/Application Support/Cursor/User/settings.json"
  ln -s "$DOTFILES_DIR/vscode-keybindings.json" "$HOME/Library/Application Support/Cursor/User/keybindings.json"
  ln -s "$DOTFILES_DIR/vscode-settings.json" "$HOME/Library/Application Support/Cursor/User/settings.json"
fi

if [ -d "$HOME/Library/Application Support/Code" ]; then
  rm -rf "$HOME/Library/Application Support/Code/User/keybindings.json"
  rm -rf "$HOME/Library/Application Support/Code/User/settings.json"
  ln -s "$DOTFILES_DIR/vscode-keybindings.json" "$HOME/Library/Application Support/Code/User/keybindings.json"
  ln -s "$DOTFILES_DIR/vscode-settings.json" "$HOME/Library/Application Support/Code/User/settings.json"
fi


if [ -d "$HOME/.config/Code" ]; then
  rm -rf "$HOME/.config/Code/User/keybindings.json"
  rm -rf "$HOME/.config/Code/User/settings.json"
  ln -s "$DOTFILES_DIR/vscode-keybindings.json" "$HOME/.config/Code/User/keybindings.json"
  ln -s "$DOTFILES_DIR/vscode-settings.json" "$HOME/.config/Code/User/settings.json"
fi
