#!/usr/bin/env bash

echo "Installing Terminals configuration..."
mkdir -p $HOME/.config/alacritty && ln -s $(pwd)/alacritty.yml $HOME/.config/alacritty/alacritty.yml
mkdir -p $HOME/.config/kitty && ln -s $(pwd)/kitty.conf $HOME/.config/kitty/kitty.conf
mkdir -p $HOME/.config/zellij && ln -s $(pwd)/config.kdl $HOME/.config/zellij/config.kdl

echo "Installing Editors configurations..."
mkdir -p $HOME/.config/nvim && ln -s $(pwd)/init.lua $HOME/.config/nvim/init.lua
mkdir -p '$HOME/Library/Application Support/Sublime Text/Packages/' && ln -s $(pwd)/SublimeText $HOME/.config/sublime-text/Packages/User
ln -s $(pwd)/.emacs $HOME/.emacs


echo "Installing Shell configurations..."
mkdir -p $HOME/.config/fish && ln -s $(pwd)/config.fish $HOME/.config/fish/config.fish

