#! /bin/bash
echo "Welcome to my world"
echo "1. vim"
echo "2. emacs"
echo "3. vscode"
echo "4. tmux"
echo "5. zsh"
echo "6. i3"
echo "0. all of above"
read -p "Enter Your choice: " choice

install_vim (){
  	echo "Installing vim/neovim configuration"
    	read -p "Do you use vim[1] or neovim[2] ? " whatvim
	if [ $whatvim -eq 1 ]; then
		ln -s ./vim/vimrc ~/.vimrc 
	elif [ $whatvim -eq 2 ]; then
		mkdir -p ~/.config/nvim
		ln -s ./vim/vimrc ~/.config/nvim/init.vim
	fi
}
install_emacs() {
  	echo "Installing Emacs configuration"
	rm -rf .emacs
	ln -s ./emacs/init.el ~/.emacs.d/init.el
}
install_vscode() {
    	echo "Installing vscode configuration"
	cp ./vscode/settings.json ~/.config/Code/User/settings.json
	cat ./vscode/extensions.txt | while read extension;do 
		code --install-extension $extension 
	done
}
install_tmux(){
  	echo "Installing tmux config"
	ln -s ./tmux/tmux.conf ~/.tmux.conf	
}
install_zsh(){
	
   	echo "Installing zsh config"
	ln ./zsh/zshrc ~/.zshrc
}
install_i3(){
	
    	echo "Installing i3 config"
	ln -s ./i3/config ~/.config/i3/config
	ln -s ./i3/i3status ~/.config/i3status/config
}
case $choice in

  1)
  	install_vim
    	;;

  2) 
  	install_emacs
    	;;

  3)
  	install_vscode
    	;;

  4)
  	install_tmux
    	;;
  
  5)
  	install_zsh
    	;;


  6)
  	install_i3
   	;;
  0)
	echo "Installing All"
  	install_vim
	install_emacs
	install_vscode
	install_tmux
	install_zsh
	install_i3
  	;;
  *)
    echo "You choose poorly ;)"
    exit 1
    ;;
esac

