#!/usr/bin/env bash

set -e

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
XDG_CONFIG="$HOME/.config"

mkdir -p "$XDG_CONFIG"

rm -rf "$XDG_CONFIG/fish" \
        "$XDG_CONFIG/ghostty" \
        "$XDG_CONFIG/alacritty" \
        "$XDG_CONFIG/starship.toml" \
        "$XDG_CONFIG/nvim" \
        "$XDG_CONFIG/wezterm" \
        "$HOME/.zshrc" \
        "$HOME/.gitconfig" \
        "$HOME/.emacs.d" \
	"$HOME/.tmux.conf" \
	"$HOME/.tmux-sessionizer"

ln -s "$DOTFILES_DIR/home/.emacs.d" "$HOME/"

ln -s "$DOTFILES_DIR/xdg_config/ghostty" "$XDG_CONFIG/"

ln -s "$DOTFILES_DIR/starship.toml" "$XDG_CONFIG/"

ln -s "$DOTFILES_DIR/home/.zshrc" "$HOME/.zshrc"

ln -s "$DOTFILES_DIR/.gitconfig" "$HOME/.gitconfig"

ln -s "$DOTFILES_DIR/xdg_config/nvim" "$XDG_CONFIG/"

ln -s "$DOTFILES_DIR/xdg_config/fish" "$XDG_CONFIG/"

ln -s "$DOTFILES_DIR/home/.tmux.conf" "$HOME/.tmux.conf"

ln -s "$DOTFILES_DIR/tmux-sessionizer" "$HOME/.tmux-sessionizer"

# VSCode (or Cursor) configs
if [ -d "$HOME/Library/Application Support/Cursor" ]; then
  rm -rf "$HOME/Library/Application Support/Cursor/User/keybindings.json"
  rm -rf "$HOME/Library/Application Support/Cursor/User/settings.json"

  ln -s "$DOTFILES_DIR/xdg_config/Code/vscode-keybindings.json" "$HOME/Library/Application Support/Cursor/User/keybindings.json"
  ln -s "$DOTFILES_DIR/xdg_config/Code/vscode-settings.json" "$HOME/Library/Application Support/Cursor/User/settings.json"
fi

if [ -d "$HOME/Library/Application Support/Code" ]; then
  rm -rf "$HOME/Library/Application Support/Code/User/keybindings.json"
  rm -rf "$HOME/Library/Application Support/Code/User/settings.json"

  ln -s "$DOTFILES_DIR/xdg_config/Code/vscode-keybindings.json" "$HOME/Library/Application Support/Code/User/keybindings.json"
  ln -s "$DOTFILES_DIR/xdg_config/Code/vscode-settings.json" "$HOME/Library/Application Support/Code/User/settings.json"
fi


if [ -d "$HOME/.config/Code" ]; then
  rm -rf "$HOME/.config/Code/User/keybindings.json"
  rm -rf "$HOME/.config/Code/User/settings.json"

  ln -s "$DOTFILES_DIR/xdg_config/Code/vscode-keybindings.json" "$HOME/.config/Code/User/keybindings.json"
  ln -s "$DOTFILES_DIR/xdg_config/Code/vscode-settings.json" "$HOME/.config/Code/User/settings.json"
fi
