#!/usr/bin/env bash

# Install base OS packages
case "$DISTRO" in
    "ubuntu")
		sudo add-apt-repository -y ppa:cppiber/hyprland
		sudo add-apt-repository -y ppa:longsleep/golang-backports
		sudo apt update && sudo apt upgrade -y


		# Install base packages
		sudo apt install -y \
			git \
			curl \
			wget \
			btop \
			hyprland \
			hypridle \
			swaylock \
			pulsemixer \
			mako-notifier \
			fish \
			alacritty \
			swaybg \
			waybar \
			wl-clipboard \
			wofi \
			swayosd \
			polkit-gnome \
			chromium \
			golang-go \
			mpv \
			fzf

		# Let wm handle these events to have more control.
		sudo tee /etc/systemd/logind.conf > /dev/null <<'EOF'
		[Login]
		HandlePowerKey=poweroff
		HandleSuspendKey=ignore
		HandleHibernateKey=ignore
		HandleLidSwitch=ignore
		HandleLidSwitchExternalPower=ignore
		KillUserProcesses=no
		IdleAction=ignore
		EOF
        ;;
    "fedora")
		set -e

		sudo dnf copr -y enable solopasha/hyprland 
		sudo dnf copr -y enable markupstart/SwayOSD
		sudo dnf copr -y enable dejan/lazygit
		sudo dnf copr -y enable azandure/clipse


		sudo dnf -y install \
			https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-42.noarch.rpm \
			https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-42.noarch.rpm

		sudo dnf groupupdate multimedia --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin
		sudo dnf -y install gstreamer1-libav gstreamer1-plugins-{base,good,bad-free,bad-free-extras,ugly} ffmpeg

		# Install base packages
		sudo dnf -y install \
			git \
			curl \
			wget \
			btop \
			hyprland \
			hypridle \
			mako \
			fish \
			alacritty \
			swaybg \
			sway \
			swayidle \
			swaylock \
			waybar \
			wl-clipboard \
			wofi \
			chromium \
			golang-go \
			dbus-devel  \
			pavucontrol \
			pkgconf-pkg-config \
			swayosd \
			mpv \
			lazygit \
			clipse \
			ripgrep \
			cmake \
			fzf


		# Install hyprshot for screenshots
		if [[ ! -f /usr/bin/hyprshot ]]; then
			sudo curl https://raw.githubusercontent.com/Gustash/Hyprshot/refs/heads/main/hyprshot > ~/hyprshot
			sudo mv ~/hyprshot /usr/bin/hyprshot
			sudo chmod +x /usr/bin/hyprshot
		fi


        ;;
    *)
        echo "Unsupported distribution: $DISTRO"
        exit 1
        ;;
esac


# Install cargo
if ! command -v cargo >/dev/null 2>&1; then
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
fi

if [[ -f "$HOME/.cargo/env" ]]; then
	. "$HOME/.cargo/env"
fi

# manage bluetooth
if ! command -v bluetui >/dev/null 2>&1; then
	cargo install bluetui
fi

# better ls
if ! command -v exa >/dev/null 2>&1; then
	cargo install exa
fi

# Prompt
if ! command -v starship >/dev/null 2>&1; then
	cargo install starship --locked
fi

# Neovim
$PLATFORM_DIR/neovim.sh

# Systemd hooks for a seamless laptop experience
sudo tee /etc/systemd/logind.conf > /dev/null <<'EOF'
[Login]
HandlePowerKey=poweroff
HandleSuspendKey=ignore
HandleHibernateKey=ignore
HandleLidSwitch=suspend
HandleLidSwitchExternalPower=suspend
HandleLidSwitchDocked=suspend
KillUserProcesses=no
IdleAction=ignore
EOF


sudo tee /etc/systemd/system/lock-before-suspend.service> /dev/null <<'EOF'
[Unit]
Description=Lock screen before suspend
Before=sleep.target
StopWhenUnneeded=true

[Service]
Type=oneshot
ExecStart=swaylock
RemainAfterExit=yes

[Install]
WantedBy=sleep.target
EOF

sudo systemctl enable lock-before-suspend.service
sudo systemctl daemon-reload
