#!/usr/bin/env bash
set -e

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
XDG_CONFIG="$HOME/.config"

rm -rf  "$XDG_CONFIG/nvim" \
	"$HOME/.tmux-sessionizer" \
	"$XDG_CONFIG/ghostty" \
	"$HOME/.tmux.conf" \
	"$XDG_CONFIG/fish" \
	"$HOME/.zshrc" \
	"$HOME/.gitconfig"

mkdir -p "$XDG_CONFIG"

ln -s "$DOTFILES_DIR/nvim" "$XDG_CONFIG/nvim"
ln -s "$DOTFILES_DIR/fish" "$XDG_CONFIG/fish"
ln -s "$DOTFILES_DIR/tmux/tmux-sessionizer" "$HOME/.tmux-sessionizer"
ln -s "$DOTFILES_DIR/ghostty" "$XDG_CONFIG/ghostty"
ln -s "$DOTFILES_DIR/.gitconfig" "$HOME/.gitconfig"
ln -s "$DOTFILES_DIR/tmux/tmux.conf" "$HOME/.tmux.conf"
ln -s "$DOTFILES_DIR/zsh/zshrc" "$HOME/.zshrc"
