#!/usr/bin/env bash
set -e

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
XDG_CONFIG="$HOME/.config"

rm -rf  "$XDG_CONFIG/nvim" \
	"$XDG_CONFIG/ghostty" \
	"$XDG_CONFIG/fish" \
	"$HOME/.gitconfig"

mkdir -p "$XDG_CONFIG"

ln -s "$DOTFILES_DIR/nvim" "$XDG_CONFIG/nvim"
ln -s "$DOTFILES_DIR/fish" "$XDG_CONFIG/fish"
ln -s "$DOTFILES_DIR/ghostty" "$XDG_CONFIG/ghostty"
ln -s "$DOTFILES_DIR/.gitconfig" "$HOME/.gitconfig"
