#!/usr/bin/env bash

set -e

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "DOTFILES_DIR $DOTFILES_DIR"

INSTALL_PACKAGES=false

# Parse args
for arg in "$@"; do
    case "$arg" in
        --with-platform)
            INSTALL_PLATFORM=true
            ;;
    esac
done

# Resolve base OS dependency
if [ "$INSTALL_PLATFORM" = true ]; then
	./platform/sync.sh
fi


# Install configs
./configs/sync.sh
