# vim:ft=kitty

## name:     Vercel
## author:   dotfiles
## license:  MIT
## blurb:    gantoreno/vscode-vercel dark — terminal on pure black.

foreground               #ededed
background               #000000
selection_foreground     #ededed
selection_background     #333333
cursor                   #ededed
cursor_text_color        #000000
url_color                #62a6ff

# Tabs
active_tab_foreground    #ffffff
active_tab_background    #262626
inactive_tab_foreground  #4f4f4f
inactive_tab_background  #000000
tab_bar_background       #000000

# Windows
active_border_color      #333333
inactive_border_color    #242424

# normal — vscode-vercel token palette
color0  #000000
color1  #f56464
color2  #58c760
color3  #f99902
color4  #62a6ff
color5  #b675f1
color6  #14cbb7
color7  #ededed

# bright
color8  #676767
color9  #f56464
color10 #58c760
color11 #f99902
color12 #62a6ff
color13 #b675f1
color14 #14cbb7
color15 #ededed
