vim.g.colors_name = "jblow"
local colors = {
  background = "#072626",
  foreground = "#d3b58d",
  selection = "#0000ff",
  keyword = "#d4d4d4",
  comment = "#118a1a",
  string = "#2ec09c",
  identifier = "#c8d4ec",
  warning = "#504038",
  constant = "#7ad0c6",
  cursor = "green",
  statusline = "#d3b58d",
  ["function"] = "#ffffff",
  macro = "#8cde94",
  punctuation = "#8cde94",
  highlight_line = "#084040",
  builtin = "#ffffff",
  error = "#ff0000",
  line_fg = "#126367",
}

local groups = {
  Normal = { fg = colors.foreground, bg = colors.background },
  NormalFloat = { fg = colors.foreground, bg = colors.background },
  Comment = { fg = colors.comment },
  Constant = { fg = colors.constant },
  String = { fg = colors.string },
  Character = { fg = colors.string },
  Number = { fg = colors["function"] },
  Boolean = { fg = colors.keyword },
  Float = { fg = colors.foreground, bg = colors.background },
  FloatBorder = { fg = colors.statusline },
  Operator = { fg = colors.punctuation },
  Keyword = { fg = colors.keyword },
  Keywords = { fg = colors.keyword },
  Identifier = { fg = colors.identifier },
  Special = { fg = colors.foreground, bg = colors.background },
  Function = { fg = colors["function"] },
  Error = { fg = colors.error },
  Todo = { fg = colors.warning, bold = true, italic = true },
  Cursor = { bg = "green" },
  CursorLineNr = { fg = colors.foreground, bold = true },
  SignColumn = { bg = colors.background },
  Conceal = { fg = colors.comment },
  CursorColumn = { bg = colors.highlight_line },
  CursorLine = { bg = colors.highlight_line },
  ColorColumn = { bg = colors.background },
  StatusLine = { fg = "black", bg = colors.statusline },
  StatusLineNC = { fg = "white" },
  StatusLineTerm = { fg = "black", bg = colors.statusline },
  StatusLineTermNC = { fg = "white", bg = colors.statusline },
  DiffAdd = { fg = colors.statusline, bg = colors.background },
  DiffChange = { fg = colors.statusline, bg = colors.background },
  DiffDelete = { fg = colors.statusline, bg = colors.background },
  DiffText = { fg = colors.statusline, bg = colors.background },
  ErrorMsg = { fg = colors.error },
  LineNr = { fg = colors.line_fg, bg = colors.background },
  Pmenu = { fg = colors.foreground, bg = colors.highlight_line },
  PmenuSel = { fg = colors.white, bg = colors.selection },
  PmenuSbar = { bg = colors.background },
  PmenuThumb = { bg = colors.selection },
  Question = { fg = colors.warning },
  QuickFixLine = { fg = colors.selection, bg = colors.background },
  TabLine = { bg = colors.highlight_line, fg = colors.foreground },
  TabLineSel = { bg = colors.background, fg = colors.foreground },
  TabLineFill = { bg = colors.background },
  Visual = { bg = colors.selection },
  VisualNOS = { fg = colors.selection },
  WarningMsg = { fg = colors.warning },
  NonText = { fg = colors.highlight_line },
}

for n, g in pairs(groups) do
  vim.api.nvim_set_hl(0, n, g)
end
