-- rf_4coder Colorscheme for Neovim
-- 4coder-fleury palette (Ryan Fleury / Casey Muratori stream look)

local transparent = vim.g.transparency

local c = {
  bg = "#0c0c0c",
  fg = "#c0a583",
  fg_dim = "#a08563",
  cursor = "#00ee00",
  keyword = "#f0c674",
  operator = "#907553",
  punctuation = "#907553",
  type = "#d8a51d",
  constant = "#6b8e23",
  number = "#ffffff",
  variable = "#c0a583",
  builtin = "#dab98f",
  macro = "#50a090",
  string = "#6b8e23",
  comment = "#504038",
  comment_pop = "#cc5735",
  function_name = "#cc5735",
  preprocessor = "#dab98f",
  warning = "#504038",
  region = "#2f2f37",
  cursorline = "#171616",
  mode_line_fg = "#cb9401",
  mode_line_bg = "#1f1f27",
  pop1 = "#70971e",
  paren_match_bg = "#e0741b",
  paren_match_fg = "#000000",
  search_bg = "#2f2f37",
  search_fg = "#f0c674",
  border = "#494949",
  surface = "#171616",
  surface_alt = "#1f1f27",
  muted = "#907553",
  dim = "#504038",
  subtle = "#907553",
  linenr_bg = "#101010",
  ghost = "#5b4d3c",
}

local function apply()
  local bg = transparent and "NONE" or c.bg
  local float_bg = bg
  local cursor_fg = transparent and c.bg or c.bg

  local highlights = {
    Normal = { fg = c.fg, bg = bg },
    NormalFloat = { fg = c.fg, bg = float_bg },
    NormalNC = { fg = c.fg_dim, bg = bg },
    Cursor = { bg = c.cursor, fg = cursor_fg },
    CursorLine = { bg = c.cursorline },
    CursorLineNr = { fg = c.mode_line_fg, bold = true, bg = c.cursorline },
    CursorColumn = { bg = c.cursorline },
    Visual = { bg = c.region },
    VisualNOS = { bg = c.region },
    LineNr = { fg = c.dim, bg = c.linenr_bg },
    LineNrAbove = { fg = c.dim, bg = c.linenr_bg },
    LineNrBelow = { fg = c.dim, bg = c.linenr_bg },
    SignColumn = { fg = c.dim, bg = bg },
    Folded = { fg = c.type, bg = c.surface },
    FoldColumn = { fg = c.muted },
    Comment = { fg = c.comment },
    SpecialComment = { fg = c.comment },

    Keyword = { fg = c.keyword },
    Function = { fg = c.function_name },
    String = { fg = c.string },
    Character = { fg = c.string },
    Type = { fg = c.type },
    Typedef = { fg = c.type },
    Variable = { fg = c.variable },
    Identifier = { fg = c.variable },
    Constant = { fg = c.constant },
    Number = { fg = c.number },
    Float = { fg = c.number },
    Boolean = { fg = c.constant },
    Operator = { fg = c.operator },
    Delimiter = { fg = c.punctuation },
    PreProc = { fg = c.preprocessor },
    Include = { fg = c.preprocessor },
    Define = { fg = c.macro },
    Macro = { fg = c.macro },
    Tag = { fg = c.type },
    Special = { fg = c.macro },
    SpecialChar = { fg = c.string },
    Title = { fg = c.fg, bold = true },
    Underlined = { fg = c.macro, underline = true },
    Error = { fg = c.comment_pop, bg = c.surface },
    Todo = { fg = c.comment_pop, bold = true },
    WarningMsg = { fg = c.warning },

    ["@keyword"] = { fg = c.keyword },
    ["@keyword.function"] = { fg = c.keyword },
    ["@keyword.import"] = { fg = c.keyword },
    ["@keyword.export"] = { fg = c.keyword },
    ["@keyword.return"] = { fg = c.keyword },
    ["@keyword.operator"] = { fg = c.keyword },
    ["@keyword.conditional"] = { fg = c.keyword },
    ["@keyword.repeat"] = { fg = c.keyword },
    ["@keyword.exception"] = { fg = c.keyword },

    ["@function"] = { fg = c.function_name },
    ["@function.builtin"] = { fg = c.function_name },
    ["@function.call"] = { fg = c.function_name },
    ["@function.method"] = { fg = c.function_name },
    ["@function.method.call"] = { fg = c.function_name },
    ["@method"] = { fg = c.function_name },
    ["@method.call"] = { fg = c.function_name },

    ["@string"] = { fg = c.string },
    ["@string.escape"] = { fg = c.number },
    ["@string.regex"] = { fg = c.macro },
    ["@string.special"] = { fg = c.string },
    ["@string.regexp"] = { fg = c.macro },
    ["@string.documentation"] = { fg = c.string },

    ["@number"] = { fg = c.number },
    ["@float"] = { fg = c.number },
    ["@boolean"] = { fg = c.constant },

    ["@constant"] = { fg = c.constant },
    ["@constant.builtin"] = { fg = c.macro },
    ["@constant.macro"] = { fg = c.macro },

    ["@type"] = { fg = c.type },
    ["@type.builtin"] = { fg = c.keyword },
    ["@type.qualifier"] = { fg = c.keyword },
    ["@type.definition"] = { fg = c.type },

    ["@variable"] = { fg = c.variable },
    ["@variable.builtin"] = { fg = c.builtin },
    ["@variable.parameter"] = { fg = c.variable },
    ["@variable.member"] = { fg = c.variable },
    ["@property"] = { fg = c.variable },
    ["@field"] = { fg = c.variable },

    ["@operator"] = { fg = c.operator },
    ["@punctuation"] = { fg = c.punctuation },
    ["@punctuation.bracket"] = { fg = c.punctuation },
    ["@punctuation.delimiter"] = { fg = c.punctuation },
    ["@punctuation.special"] = { fg = c.keyword },

    ["@comment"] = { fg = c.comment },
    ["@comment.documentation"] = { fg = c.comment },
    ["@comment.todo"] = { fg = c.comment_pop, bold = true },

    ["@tag"] = { fg = c.type },
    ["@tag.builtin"] = { fg = c.macro },
    ["@tag.attribute"] = { fg = c.variable },
    ["@tag.delimiter"] = { fg = c.punctuation },
    ["@attribute"] = { fg = c.variable },

    ["@constructor"] = { fg = c.type },
    ["@module"] = { fg = c.fg },
    ["@namespace"] = { fg = c.macro },
    ["@include"] = { fg = c.preprocessor },

    ["@label"] = { fg = c.mode_line_fg },
    ["@text"] = { fg = c.fg },
    ["@text.literal"] = { fg = c.fg },
    ["@text.title"] = { fg = c.fg, bold = true },
    ["@text.reference"] = { fg = c.type },
    ["@text.uri"] = { fg = c.constant, underline = true },
    ["@text.emphasis"] = { fg = c.fg, italic = true },
    ["@text.strong"] = { fg = c.fg, bold = true },

    ["@markup.heading"] = { fg = c.type, bold = true },
    ["@markup.link"] = { fg = c.constant, underline = true },
    ["@markup.link.url"] = { fg = c.constant, underline = true },
    ["@markup.raw"] = { fg = c.constant },
    ["@markup.italic"] = { fg = c.fg, italic = true },
    ["@markup.bold"] = { fg = c.fg, bold = true },
    ["@markup.list"] = { fg = c.mode_line_fg },

    ["@parameter"] = { fg = c.variable },
    ["@symbol"] = { fg = c.macro },
    ["@special"] = { fg = c.macro },

    DiagnosticError = { fg = c.function_name },
    DiagnosticWarn = { fg = c.type },
    DiagnosticInfo = { fg = c.constant },
    DiagnosticHint = { fg = c.comment },
    DiagnosticUnderlineError = { sp = c.function_name, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.type, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.constant, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.comment, undercurl = true },
    DiagnosticVirtualTextError = { bg = c.function_name, fg = c.paren_match_fg },
    DiagnosticVirtualTextWarn = { bg = c.type, fg = c.paren_match_fg },
    DiagnosticVirtualTextInfo = { bg = c.constant, fg = c.paren_match_fg },
    DiagnosticVirtualTextHint = { bg = c.comment, fg = c.fg },

    DiffAdd = { bg = c.surface, fg = c.constant },
    DiffChange = { bg = c.surface, fg = c.type },
    DiffDelete = { bg = c.surface, fg = c.function_name },
    DiffText = { bg = c.region, fg = c.fg },

    Headline1 = { fg = c.function_name, bg = c.surface, bold = true },
    Headline2 = { fg = c.type, bg = c.surface_alt, bold = true },
    Headline3 = { fg = c.constant, bg = c.region, bold = true },
    Headline4 = { fg = c.keyword, bg = c.surface, bold = true },
    Headline5 = { fg = c.mode_line_fg, bg = c.surface_alt, bold = true },
    Headline6 = { fg = c.fg, bg = c.surface, bold = true },

    RenderMarkdownCode = { bg = c.surface },
    RenderMarkdownCodeInline = { fg = c.constant, bg = c.surface },

    FloatBorder = { fg = c.border, bg = float_bg },
    FloatTitle = { fg = c.mode_line_fg, bg = float_bg, bold = true },
    Pmenu = { fg = c.fg, bg = float_bg },
    PmenuSel = { fg = c.paren_match_fg, bg = c.paren_match_bg },
    PmenuSbar = { bg = float_bg },
    PmenuThumb = { bg = c.subtle },
    MatchParen = { fg = c.paren_match_fg, bg = c.paren_match_bg, bold = true },
    Search = { fg = c.search_fg, bg = c.search_bg },
    IncSearch = { fg = c.search_fg, bg = c.search_bg, bold = true },
    Substitute = { fg = c.paren_match_fg, bg = c.function_name },
    WinSeparator = { fg = c.border },
    StatusLine = { fg = c.mode_line_fg, bg = c.mode_line_bg },
    StatusLineNC = { fg = c.mode_line_fg, bg = c.mode_line_bg },
    WinBar = { fg = c.mode_line_fg, bg = "NONE" },
    WinBarNC = { fg = c.dim, bg = "NONE" },
    TabLine = { fg = c.muted, bg = c.mode_line_bg },
    TabLineFill = { bg = c.mode_line_bg },
    TabLineSel = { fg = c.mode_line_fg, bg = c.bg, bold = true },

    MsgArea = { fg = c.fg, bg = bg },
    MsgSeparator = { fg = c.border, bg = bg },
    MoreMsg = { fg = c.constant },
    Question = { fg = c.constant },
    ModeMsg = { fg = c.mode_line_fg },
    EndOfBuffer = { fg = c.ghost, bg = bg },
    NonText = { fg = c.ghost },
    Whitespace = { fg = c.ghost },
    Conceal = { fg = c.ghost },
    QuickFixLine = { bg = c.cursorline },
    CurSearch = { fg = c.search_fg, bg = c.search_bg, bold = true },

    TelescopeNormal = { fg = c.fg, bg = float_bg },
    TelescopeBorder = { fg = c.border, bg = float_bg },
    TelescopePromptNormal = { fg = c.fg, bg = float_bg },
    TelescopePromptBorder = { fg = c.border, bg = float_bg },
    TelescopePromptTitle = { fg = c.mode_line_fg, bg = float_bg, bold = true },
    TelescopeSelection = { fg = c.paren_match_fg, bg = c.paren_match_bg },
    TelescopeMultiSelection = { fg = c.type, bg = float_bg },
    TelescopeResultsTitle = { fg = c.mode_line_fg, bg = float_bg, bold = true },

    FzfLuaNormal = { fg = c.fg, bg = float_bg },
    FzfLuaBorder = { fg = c.border, bg = float_bg },
    FzfLuaTitle = { fg = c.mode_line_fg, bg = float_bg, bold = true },
    FzfLuaCursor = { fg = c.paren_match_fg, bg = c.paren_match_bg },
    FzfLuaCursorLine = { bg = c.cursorline },
    FzfLuaDirPart = { fg = c.type },
    FzfLuaFilePart = { fg = c.fg },
    FzfLuaHeader = { fg = c.mode_line_fg, bold = true },
    FzfLuaHeaderText = { fg = c.keyword },
    FzfLuaInfo = { fg = c.comment },
    FzfLuaLivePrompt = { fg = c.fg, bold = true },
    FzfLuaLiveSym = { fg = c.type },
    FzfLuaPath = { fg = c.constant },
    FzfLuaPathCol = { fg = c.comment },
    FzfLuaPathLineNr = { fg = c.comment },
    FzfLuaPreviewBorder = { fg = c.border, bg = float_bg },
    FzfLuaPreviewTitle = { fg = c.mode_line_fg, bg = float_bg, bold = true },
    FzfLuaPreviewNormal = { fg = c.fg, bg = float_bg },
    FzfLuaPrompt = { fg = c.fg, bold = true },
    FzfLuaPromptBorder = { fg = c.border, bg = float_bg },
    FzfLuaPromptTitle = { fg = c.mode_line_fg, bg = float_bg, bold = true },
    FzfLuaSpinner = { fg = c.mode_line_fg },
    FzfLuaSpinnerInfo = { fg = c.constant },
    FzfLuaSpinnerTitle = { fg = c.mode_line_fg, bold = true },

    GitSignsAdd = { fg = c.constant },
    GitSignsChange = { fg = c.type },
    GitSignsDelete = { fg = c.function_name },
    GitSignsChangedelete = { fg = c.type },
    GitSignsTopdelete = { fg = c.function_name },
    GitSignsUntracked = { fg = c.comment },

    MiniDiffSignAdd = { fg = c.constant, bold = true },
    MiniDiffSignChange = { fg = c.type, bold = true },
    MiniDiffOverAdd = { bg = c.surface, fg = c.constant },
    MiniDiffOverDelete = { bg = c.surface, fg = c.function_name },
    MiniDiffOverChange = { bg = c.region, fg = c.type },

    SpellBad = { sp = c.function_name, undercurl = true },
    SpellCap = { sp = c.type, undercurl = true },
    SpellLocal = { sp = c.constant, undercurl = true },
    SpellRare = { sp = c.builtin, undercurl = true },

    BlinkCmpMenu = { fg = c.fg, bg = float_bg },
    BlinkCmpMenuBorder = { fg = c.border, bg = float_bg },
    BlinkCmpMenuSelection = { fg = c.paren_match_fg, bg = c.paren_match_bg },
    BlinkCmpDoc = { fg = c.fg, bg = float_bg },
    BlinkCmpDocBorder = { fg = c.border, bg = float_bg },
    BlinkCmpGhostText = { fg = c.muted },
    BlinkCmpKind = { fg = c.type },
    BlinkCmpLabel = { fg = c.fg },
    BlinkCmpLabelMatch = { fg = c.keyword, bold = true },
    BlinkCmpLabelDescription = { fg = c.comment },
    BlinkCmpLabelDetail = { fg = c.muted },
    BlinkCmpSource = { fg = c.comment },
    CmpItemMenu = { fg = c.comment },

    SnacksNormal = { fg = c.fg, bg = float_bg },
    SnacksWin = { fg = c.fg, bg = float_bg },
    SnacksInputNormal = { fg = c.fg, bg = float_bg },
    SnacksInputBorder = { fg = c.border, bg = float_bg },
    SnacksInputTitle = { fg = c.mode_line_fg, bg = float_bg, bold = true },
    SnacksPickerNormal = { fg = c.fg, bg = float_bg },
    SnacksPickerBorder = { fg = c.border, bg = float_bg },
    SnacksPickerTitle = { fg = c.mode_line_fg, bg = float_bg, bold = true },
    SnacksPickerList = { fg = c.fg, bg = float_bg },
    SnacksPickerSelected = { fg = c.paren_match_fg, bg = c.paren_match_bg },
    SnacksPickerDir = { fg = c.type },
    SnacksPickerMatch = { fg = c.keyword, bold = true },

    OilFloat = { fg = c.fg, bg = float_bg },
    OilBorder = { fg = c.border, bg = float_bg },
    OilDirHidden = { fg = c.dim },
    OilDirIcon = { fg = c.type },
    OilDir = { fg = c.type },
    OilFile = { fg = c.fg },
    OilHidden = { fg = c.dim },
    OilLink = { fg = c.constant, underline = true },
    OilLinkTarget = { fg = c.constant },
    OilLinkPath = { fg = c.comment },
    OilParent = { fg = c.mode_line_fg },
    OilSelected = { fg = c.paren_match_fg, bg = c.paren_match_bg },

    TreesitterContext = { fg = c.muted, bg = c.surface },
    TreesitterContextBottom = { fg = c.border, bg = c.surface },

    LspReferenceText = { bg = c.region },
    LspReferenceRead = { bg = c.region },
    LspReferenceWrite = { bg = c.region },
    LspSignatureActiveParameter = { fg = c.keyword, bold = true },

    TermCursor = { bg = c.cursor, fg = cursor_fg },
    TermCursorNC = { bg = c.dim, fg = cursor_fg },

    VertSplit = { fg = c.border },
    ColorColumn = { bg = c.surface },
    Ignore = { fg = c.dim },
    SpecialKey = { fg = c.dim },
    Vert = { fg = c.border },

    NeogitBranch = { fg = c.type },
    NeogitRemote = { fg = c.constant },
    NeogitHunkHeader = { fg = c.mode_line_fg, bg = c.surface },
    NeogitHunkHeaderHighlight = { fg = c.paren_match_fg, bg = c.paren_match_bg },
    NeogitDiffAdd = { fg = c.constant },
    NeogitDiffDelete = { fg = c.function_name },
    NeogitDiffContext = { fg = c.fg },
    NeogitPopupBranchName = { fg = c.type, bold = true },

    MasonHeader = { fg = c.mode_line_fg, bg = c.mode_line_bg, bold = true },
    MasonHighlight = { fg = c.constant },
    MasonHighlightBlock = { fg = c.paren_match_fg, bg = c.constant },
    MasonHighlightBlockBold = { fg = c.paren_match_fg, bg = c.constant, bold = true },
    MasonMuted = { fg = c.comment },
    MasonMutedBlock = { fg = c.fg, bg = c.surface },

    WhichKey = { fg = c.type },
    WhichKeyGroup = { fg = c.mode_line_fg },
    WhichKeyDesc = { fg = c.fg },
    WhichKeySeparator = { fg = c.punctuation },
    WhichKeyFloat = { fg = c.fg, bg = float_bg },
    WhichKeyBorder = { fg = c.border, bg = float_bg },
    WhichKeyTitle = { fg = c.mode_line_fg, bg = float_bg, bold = true },

    NotifyINFO = { fg = c.constant },
    NotifyWARN = { fg = c.type },
    NotifyERROR = { fg = c.function_name },
    NotifyDEBUG = { fg = c.comment },
    NotifyTRACE = { fg = c.dim },
    NotifyBackground = { bg = float_bg },

    BufferLineFill = { bg = c.mode_line_bg },
    BufferLineBackground = { fg = c.muted, bg = c.mode_line_bg },
    BufferLineBufferVisible = { fg = c.fg, bg = c.mode_line_bg },
    BufferLineBufferSelected = { fg = c.mode_line_fg, bg = c.bg, bold = true },
    BufferLineIndicatorSelected = { fg = c.mode_line_fg, bg = c.bg },
    BufferLineTab = { fg = c.muted, bg = c.mode_line_bg },
    BufferLineTabSelected = { fg = c.mode_line_fg, bg = c.bg, bold = true },
    BufferLineTabClose = { fg = c.function_name, bg = c.mode_line_bg },

    NvimTreeNormal = { fg = c.fg, bg = bg },
    NvimTreeRootFolder = { fg = c.mode_line_fg, bold = true },
    NvimTreeFolderName = { fg = c.type },
    NvimTreeFolderIcon = { fg = c.type },
    NvimTreeEmptyFolderName = { fg = c.dim },
    NvimTreeIndentMarker = { fg = c.dim },
    NvimTreeGitDirty = { fg = c.type },
    NvimTreeGitStaged = { fg = c.constant },
    NvimTreeGitMerge = { fg = c.builtin },
    NvimTreeGitRenamed = { fg = c.constant },
    NvimTreeGitDeleted = { fg = c.function_name },
    NvimTreeGitNew = { fg = c.constant },

    HelpCommand = { fg = c.keyword },
    HelpExample = { fg = c.string },
    HelpHeader = { fg = c.mode_line_fg, bold = true },
    HelpHyperTextJump = { fg = c.constant, underline = true },
    HelpHyperTextEntry = { fg = c.constant },
    HelpKey = { fg = c.type },
    HelpSpecial = { fg = c.macro },
    HelpSectionDelim = { fg = c.border },

    ManSubHeading = { fg = c.mode_line_fg, bold = true },
    ManOptionDesc = { fg = c.type },
    ManHeader = { fg = c.function_name, bold = true },

    healthSuccess = { fg = c.constant },
    healthWarning = { fg = c.type },
    healthError = { fg = c.function_name },
  }

  for group, opts in pairs(highlights) do
    vim.api.nvim_set_hl(0, group, opts)
  end
end

apply()
vim.g.colors_name = "rf_4coder"
