theme = "rose_pine"

[editor]
bufferline = 'multiple'
line-number = 'relative'
cursorline = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "version-control", "position", "position-percentage"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true


[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[keys.insert]
j = { k = "normal_mode"}
k = { j = "normal_mode"}
