theme = "base16_transparent"

[editor]
bufferline = 'multiple'
line-number = 'relative'
cursorline = true

[editor.statusline]
left = ["mode", "spinner"]
right = ["file-name", "diagnostics", "version-control", "position", "position-percentage"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true

[editor.lsp]
display-inlay-hints = true


[editor.cursor-shape]
normal = "block"
select = "underline"

[keys.insert]
C-c = "normal_mode"
j = {k = "normal_mode"}