theme = "tokyonight"

[editor]
line-number = "relative"
bufferline = "multiple"

[keys.insert]
j = { k = "normal_mode"}
k = { j = "normal_mode"}

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
