# Everforest Dark Hard

background #1e2326
foreground #d3c6aa
selection_background #4c3743
selection_foreground #d3c6aa

cursor #a7c080
cursor_text_color #272e33

url_color #7fbbb3

# black
color0 #414b50
color8 #475258

# red
color1 #e67e80
color9 #e67e80

# green
color2 #a7c080
color10 #a7c080

# yellow
color3 #dbbc7f
color11 #dbbc7f

# blue
color4 #7fbbb3
color12 #7fbbb3

# magenta
color5 #d699b6
color13 #d699b6

# cyan
color6 #83c092
color14 #83c092

# white
color7 #d3c6aa
color15 #d3c6aa

# extra
active_border_color #a7c080
inactive_border_color #414b50
bell_border_color #e67e80
