# vim:ft=kitty
#: Paradiso Dark theme by BrokenSideViewMirror.

## name: Paradiso Dark
## author: BrokenSideViewMirror (https://github.com/BrokenSideViewMirror)
## license: MIT
## upstream: https://github.com/BrokenSideViewMirror/paradiso-theme-kitty/blob/main/themes/paradiso-dark.conf
## blurb: A more relaxed, tranquil dark mode theme for your terminal. For more information, it is a tritone of pink, cyan, and purple with an influence from pastel colors.

#: The basic colors

foreground                      #b8d0db
background                      #302138
selection_foreground            #1e1423
selection_background            #d7bee5


#: Cursor colors

cursor                          #89a7bf
cursor_text_color               #232438
cursor_trail_color              #9699ce


#: URL underline color when hovering with mouse

url_color                       #c2e2fc


#: kitty window border colors and terminal bell colors

active_border_color             #c2c5fc
inactive_border_color           #513d5b
bell_border_color               #fcabfb
visual_bell_color               none


#: OS Window titlebar colors

wayland_titlebar_color          #625c84
macos_titlebar_color            #625c84


#: Tab bar colors

active_tab_foreground           #353d44
active_tab_background           #4e6170
inactive_tab_foreground         #302138
inactive_tab_background         #533b60
tab_bar_background              #483354
tab_bar_margin_color            none


#: Colors for marks (marked text in the terminal)

mark1_foreground #5e6c77
mark1_background #c2e2fc
mark2_foreground #685d59
mark2_background #f2dcd3
mark3_foreground #603e60
mark3_background #fcabfb


#: The basic 16 colors

#: black
color0 #553a63
color8 #6f4c82

#: red
color1 #8eb8db
color9 #c2e1fc

#: green
color2  #8e92db
color10 #c2c4fc

#: yellow
color3  #9157cc
color11 #c68ffc

#: blue
color4  #4660a0
color12 #5d8afc

#: magenta
color5  #db74e0
color13 #f8aefc

#: cyan
color6  #68acc1
color14 #99e5fc

#: white
color7  #b8d0db
color15 #ccebf9


#: You can set the remaining 240 colors as color16 to color255.
