set modeline
set smartcase
set nocompatible 
set encoding=utf-8
set history=700
set hlsearch
set ruler
set mouse=a
set wrap
set autoindent
set termguicolors
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set nobackup
set nowritebackup
set noswapfile
set splitright
set splitbelow
set relativenumber
set number
set clipboard=unnamedplus
set hidden
