" General Settings{{{
filetype off
" Syntax highlight
syntax on
" enable filetype plugin loading
filetype indent plugin on

" Case insensitive
set ignorecase
" ??
set modeline
" vi Incompatible defaults 
set nocompatible
" Default encoding to UTF-8
set encoding=utf-8
" Highlight search result in pattern search
set hlsearch
" Command history capacity
set history=700
" Maximum number of tabs to be opened
set tabpagemax=100
" Show column and line number in status bar
set ruler
" Enable mouse support
set mouse=a
" Enable line numbers
set nu 
" Set <leader> to SPC
let mapleader = " "
" Disable line wrapping in long lines
set nowrap
" Start new line with same indent level as current line
set autoindent
noremap j gj
noremap k gk

" Relative line numbers
set relativenumber
" Terminal Colors
set termguicolors

" General Tab settings {{{
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
" }}}

"Easier window navigation {{{
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l
map <C-h> <C-w>h
" }}}

map Q <nop>

" Map ; to : for simpler command execuation
map ; :
" }}}

" Disable highlight after search
nmap <leader>/ :nohl<CR>

" Exit Insert mode more easily {{{
inoremap jk <esc>
inoremap kj <esc> 
" }}}

" Make copy/pase normal
set clipboard=unnamedplus

" Plugins
call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'honza/dockerfile.vim'
Plug 'ziglang/zig.vim'
Plug 'dag/vim-fish'
Plug 'rust-lang/rust.vim'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'michaeljsmith/vim-indent-object'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-jdaddy'
Plug 'tpope/vim-commentary' 
Plug 'LnL7/vim-nix'
Plug 'dyng/ctrlsf.vim'
Plug 'tpope/vim-fugitive'
call plug#end()


map <leader><leader> :FZF<CR>
nnoremap // :BLines<CR>
nnoremap ?? :Rg<CR>
let g:fzf_layout = { 'window': { 'width': 0.95, 'height': 0.95 } }

command! Config :e "$HOME/.vimrc"
