#! /bin/sh
# kill already running polybar
pkill polybar

# Autostart applications
sxhkd &
picom &
polybar example &
# Desktops and monitors
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9

# Keyboard layout
setxkbmap -layout us,ir -option "ctrl:nocaps" -option "grp:shifts_toggle"

# move polybar down in fullscreen mode
xdo above -t $(xdo id -n root) $(xdo id -a polybar)

# set wallpaper
feh --bg-fill ~/w/dotfiles/wallpapers/darksideofthemoon.png
