#! /bin/sh



# kill already running polybar
pkill polybar
pkill comton
pkill dunst

# Autostart applications
sxhkd &
compton &
polybar default &
xfce4-power-manager &
dunst &

# Desktops and monitors
bspc monitor eDP-1 --reset-desktops dev www music movie chat steam 7 8 9 

# Keyboard layout
setxkbmap -layout us,ir -option "ctrl:nocaps" -option "grp:shifts_toggle"

# move polybar down in fullscreen mode
xdo above -t $(xdo id -n root) $(xdo id -a polybar)

# set wallpaper
nitrogen --set-zoom-fill --random ~/w/dotfiles/wallpapers/

# Some values
bspc config top_padding 30
bspc config window_gap 3 
bspc config border_width 1 
bspc config bottom_padding 0
bspc config borderless_monocle true
