(deftheme handmadehero)
(let ((background          "#161616")
	(highlight           "midnight blue")
	(region              "medium blue")
	(text                "#cdaa7d")
	(keyword             "DarkGoldenrod3")
	(comment             "gray50")
	(string              "olive drab")
	(variable            "burlywood3")
	(warning             "#504038")
	(constant            "olive drab")
	(cursor              "green")
	(function            "burlywood3")
	(macro               "#8cde94")
	(punctuation         "burlywood3")
	(builtin             "#DAB98F"))

    (custom-set-faces
     `(default                          ((t (:foreground ,text :background ,background))))
     `(cursor                           ((t (:background ,cursor))))
     `(font-lock-keyword-face           ((t (:foreground ,keyword))))
     `(font-lock-type-face              ((t (:foreground ,punctuation))))
     `(font-lock-constant-face          ((t (:foreground ,constant))))
     `(font-lock-variable-name-face     ((t (:foreground ,variable))))
     `(font-lock-builtin-face           ((t (:foreground ,builtin))))
     `(font-lock-string-face            ((t (:foreground ,string))))
     `(font-lock-comment-face           ((t (:foreground ,comment))))
     `(font-lock-comment-delimiter-face ((t (:foreground ,comment))))
     `(font-lock-doc-face               ((t (:foreground ,comment))))
     `(font-lock-function-name-face     ((t (:foreground ,function))))
     `(font-lock-doc-string-face        ((t (:foreground ,string))))
     `(font-lock-preprocessor-face      ((t (:foreground ,macro))))
     `(font-lock-warning-face           ((t (:foreground ,warning))))
     `(region                           ((t (:background ,region))))
     `(hl-line                          ((t (:background ,highlight))))
     `(vertico-current                  ((t (:inherit hl-line))))
     `(mode-line                        ((t (:background "#ffffff" :foreground "#000000"))))
     `(mode-line-inactive               ((t (:background "gray20" :foreground "#ffffff"))))
     `(show-paren-match                 ((t (:background "burlywood3" :foreground "black"))))
     `(highlight                        ((t (:foreground nil :background ,region))))))

(provide 'handmadehero)
