[colors.primary]
background = "#0a0f1a"  # Deep ocean black-blue
foreground = "#a8dfff"  # Icy azure glow

[colors.cursor]
cursor = "#00ccff"      # Electric cyan beam
text = "#0a0f1a"        # Dark contrast

[colors.normal]
black   = "#0d1b26"     # Abyssal navy
red     = "#0099cc"     # Bright cerulean
green   = "#00e0b8"     # Tropical aqua
yellow  = "#33ccff"     # Sky flash
blue    = "#00aaff"     # Bold azure
magenta = "#3399ff"     # Deep sky fusion
cyan    = "#66e0ff"     # Frosted cyan
white   = "#cceeff"     # Snow drift

[colors.bright]
black   = "#123247"     # Steel blue shadow
red     = "#33ccff"     # Neon sky
green   = "#33ffdd"     # Glacial mint
yellow  = "#66ddff"     # Arc light
blue    = "#33bbff"     # Vibrant azure
magenta = "#66b2ff"     # Cloud-washed blue
cyan    = "#99eeff"     # Crystal haze
white   = "#ffffff"     # Pure white glow

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 11.0

[window]
padding.x = 10
padding.y = 10
opacity = 0.95

