require("amirreza.options")
require("amirreza.statusline")
require("amirreza.keymaps")
require("amirreza.terminal")
require("amirreza.lsp")
require("amirreza.util")
require("amirreza.install_plugins")
