--    ___         _                      ___       __
--   / _ | __ _  (_)__________ ___ ___ _/ _ | ___ / /__
--  / __ |/  ' \/ / __/ __/ -_)_ // _ `/ __ |(_-</  '_/
-- /_/ |_/_/_/_/_/_/ /_/  \__//__/\_,_/_/ |_/___/_/\_\
--
-- AmirrezaAsk neovim configuration
-- Structure:
-- list of installed plugins in plugin/plugins.lua
-- List of basic neovim options in plugin/options.lua
-- after/plugin contains configuration for installed plugins
-- some helpers and simple utilities in lua/*.lua
