#!/bin/bash
go install "mvdan.cc/gofumpt@latest"
go install "github.com/segmentio/golines@latest"
go install "golang.org/x/tools/cmd/goimports@latest"
go install "golang.org/x/tools/cmd/gorename@latest"
go install "github.com/fatih/gomodifytags@Latest"
go install "github.com/cweill/gotests@latest"
go install 'github.com/koron/iferr@latest'
go install 'github.com/josharian/impl@latest'
go install 'github.com/davidrjenni/reftools/cmd/fillstruct@latest'
go install 'github.com/davidrjenni/reftools/cmd/fixplurals@latest'
go install 'github.com/davidrjenni/reftools/cmd/fillswitch@latest'
go install 'github.com/go-delve/delve/cmd/dlv@latest'
go install 'github.com/onsi/ginkgo/ginkgo@latest'
go install 'github.com/kyoh86/richgo@latest'

DOWNLOAD_URL=$(curl -s https://api.github.com/repos/JohnnyMorganz/StyLua/releases/latest \
        | grep browser_download_url \
        | grep macos \
        | cut -d '"' -f 4)

curl -L $DOWNLOAD_URL > stylua.zip
unzip stylua.zip
mkdir -p ~/.local/bin
mv stylua ~/.local/bin/stylua
chmod +x ~/.local/bin/stylua
rm stylua.zip

