install:
	echo "@ Installing Amirreza neovim "
	echo "@ Make sure you have neovim 0.5 or higher "
	git clone --depth 1 https://github.com/wbthomason/packer.nvim ${HOME}/.local/share/nvim/site/pack/packer/start/packer.nvim	
	./scripts/install_go_tools.sh
	./scripts/install_stylua.sh
	./scripts/install_sumneko.sh

