colorscheme gruvbox-dark

# Install plugin manager
evaluate-commands %sh{
        plugins="$kak_config/plugins"
            mkdir -p "$plugins"
                [ ! -e "$plugins/plug.kak" ] && \
                        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
                            printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}

# Plugins
plug "andreyorst/plug.kak" noload
plug "andreyorst/fzf.kak"
map global normal <c-p> ': fzf-mode<ret>'


