#!/usr/bin/env bash

# Copy pasta from https://github.com/basecamp/omarchy/blob/master/default/bash/shell

shopt -s histappend
HISTCONTROL=ignoreboth
HISTSIZE=32768
HISTFILESIZE="${HISTSIZE}"

# Autocompletion
if [[ ! -v BASH_COMPLETION_VERSINFO && -f /usr/share/bash-completion/bash_completion ]]; then
  source /usr/share/bash-completion/bash_completion
fi

# Set complete path
export PATH="./bin:$HOME/.local/bin:$PATH"
set +h

