#!/usr/bin/env bash

filename=`echo $samfile`

extension=`echo "${filename##*.}"`

if [ $extension == "go" ]; then
	awk '{print "//" $0}'
elif [ $extension == "sh" ] || [ $extension == "bash" ] || [ $extension == "zsh" ] || [ $extension == "fish" ] || [ $extension == "py" ]; then
	awk '{print "#" $0}'
else
	awk '{print "#" $0}'
fi


