#!/usr/bin/bash
filename=`echo $samfile`

extension=`echo "${filename##*.}"`

if [ $extension == 'go' ]; then
	cmd='go run *.go'
fi
eval $cmd
exit_status=$?

if [[ $exit_status -ne 0 ]]; then
	echo "============ Run Failed ============"
else
	echo "============ Run Succeded ============"
fi