[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
# The primary colors for the terminal window
background = '#0A1428'
foreground = '#F0F8FF'

[colors.cursor]
text = 'CellBackground'
cursor = 'CellForeground'

[colors.normal]
# Normal colors used by applications
black = '#0A1428'
red = '#FF40A3'
green = '#00BFFF'
yellow = '#6A90D2'
blue = '#BDBDBD'
magenta = '#FF40A3'
cyan = '#BDBDBD'
white = '#BDBDBD'

[colors.bright]
# Bright colors used for emphasis
black = '#BDBDBD'
red = '#FF40A3'
green = '#00BFFF'
yellow = '#6A90D2'
blue = '#00BFFF'
magenta = '#FF40A3'
cyan = '#00BFFF'
white = '#00BFFF'
