#!/usr/bin/env bash

# Kiro CLI pre block. Keep at the top of this file.
[[ -f "${HOME}/Library/Application Support/kiro-cli/shell/bashrc.pre.bash" ]] && builtin source "${HOME}/Library/Application Support/kiro-cli/shell/bashrc.pre.bash"


[[ $- == *i* ]] && bind -f ~/.config/bash/inputrc
source ~/.config/bash/envs
source ~/.config/bash/aliases
source ~/.config/bash/functions
source ~/.config/bash/prompt

. "$HOME/.cargo/env"


# Kiro CLI post block. Keep at the bottom of this file.
[[ -f "${HOME}/Library/Application Support/kiro-cli/shell/bashrc.post.bash" ]] && builtin source "${HOME}/Library/Application Support/kiro-cli/shell/bashrc.post.bash"
