#! /bin/bash

code --install-extension adpyke.vscode-sql-formatter
code --install-extension alexcvzz.vscode-sqlite
code --install-extension amiralizadeh9480.laravel-extra-intellisense
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension bungcip.better-toml
code --install-extension eamodio.gitlens
code --install-extension evgeniypeshkov.syntax-highlighter
code --install-extension golang.go
code --install-extension Gruntfuggly.todo-tree
code --install-extension hashicorp.terraform
code --install-extension JakeBecker.elixir-ls
code --install-extension liuchao.go-struct-tag
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.python
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.powershell
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension PKief.material-icon-theme
code --install-extension plex.vscode-protolint
code --install-extension premparihar.gotestexplorer
code --install-extension quicktype.quicktype
code --install-extension redhat.vscode-yaml
code --install-extension rust-lang.rust
code --install-extension saratravi.elixir-formatter
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wholroyd.HCL
code --install-extension yamatsum.vscode-nonicons
code --install-extension zxh404.vscode-proto3
