$env:GOPROXY = "https://repo.snapp.tech/repository/goproxy,goproxy.io,direct"
$env:GOPRIVATE = "https://gitlab.snapp.ir"
$env:GOPATH = "$HOME"
$env:DOTFILES = "~/src/repos/Personal/dotfiles/"
$env:PATH += ":$HOME/.local/lua-language-server/bin/Linux:$env:GOPATH/bin:$HOME/.local/bin:$HOME/.config/composer/vendor/bin:$HOME/.cargo/bin"
