#!/usr/bin/env bash

unlink current
ln -s $1 current

hyprctl reload
pkill waybar; waybar &2>/dev/null &
pkill swaybg; swaybg -i ./current/backgrounds/$(ls ./current/backgrounds/ | head -n 1) &2>/dev/null &
