#!/usr/bin/env bash

THEMES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

unlink $THEMES_DIR/current
ln -s $1 $THEMES_DIR/current

hyprctl reload

pkill waybar; waybar &2>/dev/null &

pkill swaybg; swaybg -i $THEMES_DIR/current/backgrounds/$(ls $THEMES_DIR/current/backgrounds/ | head -n 1) &2>/dev/null &

unlink ~/.config/nvim/lua/theme-manager.lua; ln -s $THEMES_DIR/current/neovim.lua ~/.config/nvim/lua/theme-manager.lua

gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

touch ~/.config/alacritty/alacritty.toml
