if ! test -d $HOME/.oh-my-zsh 
then
    git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
fi

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(git)

source $ZSH/oh-my-zsh.sh

reload() {
    source ~/.zshrc
}

if command -v nvim &> /dev/null
then
    alias vim='nvim'
fi

if command -v cursor &> /dev/null
then
    alias code='cursor'
fi

if ! command -v starship &> /dev/null
then
    curl -sS https://starship.rs/install.sh | sh
fi

eval "$(starship init zsh)"


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source ~/.profile


alias artisan='php artisan'

alias wip='git add . && git commit -m "Work In Progress" && git push origin $(git_current_branch)'
alias gs='git status'
alias nah='git stash'
alias ok='git add . && git commit'

export PATH="/Users/amirrezaask/.config/herd-lite/bin:$PATH"
export PHP_INI_SCAN_DIR="/Users/amirrezaask/.config/herd-lite/bin:$PHP_INI_SCAN_DIR"

export EDITOR='nvim'
# export EDITOR='code -w'
export GIT_EDITOR="$EDITOR"
