if ! test -d $HOME/.oh-my-zsh 
then
    git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
fi
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="cloud"

plugins=(git)

source $ZSH/oh-my-zsh.sh

reload() {
    source ~/.zshrc
}

tns() {
    if [[ ! -z $1 ]]; then
        tmux new-session -d -s"$1"
        tmux switch-client -t"$1"
    fi
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source ~/.profile

# if command -v starship &>/dev/null
# then
#     eval "$(starship init zsh)"
# fi


sync-repos () {
    find . -type d -name '.git' -execdir sh -c 'echo "Pulling in $PWD"; git pull' \;
}

alias wip='git add . && git commit -m "wip" && git push origin $(git_current_branch)'

alias gs='git status'
export PATH="/Users/amirrezaask/.config/herd-lite/bin:$PATH"
export PHP_INI_SCAN_DIR="/Users/amirrezaask/.config/herd-lite/bin:$PHP_INI_SCAN_DIR"
