if ! test -d $HOME/.oh-my-zsh 
then
    git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
fi
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=()

source $ZSH/oh-my-zsh.sh

reload() {
    source ~/.zshrc
}

tns() {
    if [[ ! -z $1 ]]; then
        tmux new-session -d -s"$1"
        tmux switch-client -t"$1"
    fi
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source ~/.profile

if command -v starship &>/dev/null
then
    eval "$(starship init zsh)"
fi


