#!/usr/bin/env bash
source ~/.config/zsh/vars.zsh
export PLAN9='/usr/local/plan9'
export PATH="$PLAN9/bin:$PATH"
export ACME="/home/amirreza/src/github.com/amirrezaask/dotfiles/acme"
export SHELL=rc
FONT='GoMono'
SIZE='11'
plumbproc=$(ps ax | grep -v grep | grep plumber)
if [ -z "$plumbproc" ]; then
    9 plumber
fi
fontsrvproc=$(ps ax | grep -v grep | grep fontsrv)
if [ -z "$fontsrvproc" ]; then
    9 fontsrv -m /mnt/font &
fi

9term -c -f "/mnt/font/$FONT/${SIZE}a/font"
