#!/usr/bin/env bash
export PLAN9='/usr/local/plan9'
export PATH="$PLAN9/bin:$PATH"
export SHELL=rc

plumbproc=$(ps ax | grep -v grep | grep plumber)
if [ -z "$plumbproc" ]; then
    9 plumber
fi

/usr/local/plan9/bin/acme -a -f /mnt/font/JetBrainsMonoNerdFontCompleteM-Regular/13a/font 2>/dev/null 1>/dev/null &
