#!/usr/bin/env bash
source ~/.config/zsh/vars.zsh
export PLAN9='/usr/local/plan9'
export PATH="$PLAN9/bin:$PATH"
export ACME="/home/amirreza/src/github.com/amirrezaask/dotfiles/acme"
export SHELL=rc
FONT='JetBrainsMonoNerdFontCompleteM-Regular'
FONTSIZE='10'
plumbproc=$(ps ax | grep -v grep | grep plumber)
if [ -z "$plumbproc" ]; then
    9 plumber
fi
fontsrvproc=$(ps ax | grep -v grep | grep fontsrv)
if [ -z "$fontsrvproc" ]; then
    9 fontsrv -m /mnt/font &
fi
export DISPLAY=':0'
/usr/local/plan9/bin/acme -a -f "/mnt/font/$FONT/${FONTSIZE}a/font" 2>/dev/null 1>/dev/null &
#/usr/local/plan9/bin/acme -a -f "/mnt/font/$FONT/11a/font"
