theme = "onedark"

[keys.insert]
"j" = { "k" = "normal_mode" }

[keys.normal.space]
space = "file_picker"

[editor]
cursorline = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
