#!/usr/bin/env bash

if [[ -z "$TMUX" ]]; then
    echo "Need to be inside tmux session."
    exit 1
fi


if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/w -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

tmux neww -c $selected -n $selected_name
