source ~/w/dotfiles/zsh/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle zsh-users/zsh-autosuggestions 
antigen bundle terraform
antigen theme cloud 
antigen apply

# aliases
export DOTFILES="$HOME/w/dotfiles"
export GO111MODULE='on'
export GOPATH="$HOME/go"
export PYTHONBINS="$HOME/.local/bin"
export EDITOR='nvim'
export GOPRIVATE='gitlab.snapp.ir,gitlab.com,git.espadev.ir'
export GOPROXY='goproxy.io'
export PLAN9="$HOME/.local/plan9"
# export _JAVA_AWT_WM_NONREPARENTING=1
export PATH="/usr/local/go/bin:$HOME/.config/composer/vendor/bin:$GOROOT/bin:$GOPATH/bin:$HOME/.cargo/bin:$PYTHONBINS:/usr/local/Postman:$HOME/.local/elixir-ls/:$PATH"

alias open='xdg-open'
alias snappvpn="sudo openfortivpn -c $HOME/snappDC.conf"
alias lg='lazygit'
alias g='git status'
alias dots="cd $DOTFILES"
alias lock='i3lock -c000000'
alias gd='git diff | batcat'
alias tf='terraform'
alias tg='terragrunt'
alias octl='kubectl --kubeconfig ~/.order/kubeconfig'

if type nvim > /dev/null 2>&1; then
    alias vim='nvim'
    alias vi='nvim'
fi
# setxkbmap -layout "us,ir" -option "grp:shifts_toggle" -option "ctrl:nocaps"
export DISPLAY="`grep nameserver /etc/resolv.conf | sed 's/nameserver //'`:0"

