export ZSH="/home/$(whoami)/.oh-my-zsh"
source $GOPATH/src/github.com/amirrezaask/dotfiles/zsh/vars.zsh

ZSH_THEME="ys"

plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh
