#! /bin/bash
rm -rf ~/.emacs.d
mkdir ~/.emacs.d
ln -s "$(pwd)/init.el" ~/.emacs.d/init.el
ln -s "$(pwd)/early-init.el" ~/.emacs.d/early-init.el
ln -s "$(pwd)/lisp" ~/.emacs.d/lisp
ln -s "$(pwd)/site-lisp" ~/.emacs.d/site-lisp

