[[keyboard.bindings]]
key = "Key1"
mods = "Command"
chars = "\x011"

[[keyboard.bindings]]
key = "Key2"
mods = "Command"
chars = "\x012"

[[keyboard.bindings]]
key = "Key3"
mods = "Command"
chars = "\x013"

[[keyboard.bindings]]
key = "Key4"
mods = "Command"
chars = "\x014"

[[keyboard.bindings]]
key = "Key5"
mods = "Command"
chars = "\x015"

[[keyboard.bindings]]
key = "Key6"
mods = "Command"
chars = "\x016"

[[keyboard.bindings]]
key = "Key7"
mods = "Command"
chars = "\x017"

[[keyboard.bindings]]
key = "Key8"
mods = "Command"
chars = "\x018"

[[keyboard.bindings]]
key = "Key9"
mods = "Command"
chars = "\x019"
