[env]
TERM = "xterm-256color"


[font]
normal = { family = "Maple Mono" }
bold   = { family = "Maple Mono" }
italic = { family = "Maple Mono" }
size   = 12

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.97
dynamic_title = false

[keyboard]
bindings = [
	{ key = "F11", action = "ToggleFullscreen" }
]

[general]
import = [ "~/.config/current-theme/alacritty.toml" ]
live_config_reload = true
